import{useState}from'react';import{Check,Play,RotateCcw}from'lucide-react';import'./advancedGitLab.css';
type Scenario={name:string;goal:string;commands:string[];frames:string[];explain:string[]};
const scenarios:Scenario[]=[
{name:'Reset',goal:'Mover HEAD e entender o que acontece com as alterações.',commands:['git reset --soft HEAD~1','git reset --mixed HEAD~1','git reset --hard HEAD~1'],frames:['A──B──C ← HEAD','A──B ← HEAD · C sai do histórico · mudanças ficam staged','A ← HEAD · mudanças voltam ao working','A ← HEAD · alterações de B são descartadas'],explain:['Estado inicial: três commits locais.','--soft move HEAD, mas preserva as mudanças na Staging Area.','--mixed também limpa o stage e mantém as mudanças no Working Directory.','--hard move HEAD e descarta alterações rastreadas. É a opção destrutiva.']},
{name:'Revert',goal:'Desfazer um commit sem reescrever o histórico compartilhado.',commands:['git revert C'],frames:['A──B──C ← origin/main','A──B──C──C⁻¹ ← HEAD'],explain:['C já foi compartilhado no remoto.','revert cria um novo commit inverso. C continua visível no histórico.']},
{name:'Stash',goal:'Guardar trabalho incompleto para trocar de contexto.',commands:['git stash push -m "wip login"','git switch hotfix','git stash pop'],frames:['working: login.ts ✎','working limpo · stash: [wip login]','branch: hotfix · stash preservado','working: login.ts ✎ · stash vazio'],explain:['Há alterações ainda sem commit.','stash retira temporariamente as mudanças do Working Directory.','Agora é seguro mudar de branch.','stash pop reaplica e remove a entrada do stash.']},
{name:'Rebase',goal:'Reposicionar commits da feature sobre a main atualizada.',commands:['git rebase main'],frames:['main A──B──C\n      ╲D──E feature','main A──B──C──D′──E′ feature'],explain:['A feature nasceu em B, enquanto main avançou para C.','rebase recria D e E sobre C. Por isso os novos commits têm novos hashes.']},
{name:'Cherry-pick',goal:'Trazer apenas um commit específico de outra branch.',commands:['git cherry-pick X'],frames:['main A──B\nfeature ╲──X──Y','main A──B──X′\nfeature ╲──X──Y'],explain:['A feature contém X e Y, mas main precisa somente do hotfix X.','cherry-pick reaplica a mudança de X como um novo commit X′ em main.']},
{name:'Restore',goal:'Desfazer alterações de arquivo ou retirar algo do stage.',commands:['git restore --staged app.ts','git restore app.ts'],frames:['staged: app.ts ✓','working: app.ts ✎ · staged vazio','working limpo'],explain:['app.ts está preparado para commit.','--staged remove do stage sem apagar a edição.','restore sem --staged restaura o arquivo rastreado a partir do índice.']}
];
export default function AdvancedGitLab(){const[idx,setIdx]=useState(0);const[step,setStep]=useState(0);const s=scenarios[idx];const max=s.frames.length-1;function choose(i:number){setIdx(i);setStep(0)}return <section className="advanced"><div className="advancedTabs">{scenarios.map((x,i)=><button className={i===idx?'on':''} onClick={()=>choose(i)} key={x.name}>{x.name}</button>)}</div><div className="advancedHero"><small>GIT ADVANCED LAB</small><h2>{s.name}</h2><p>{s.goal}</p></div><article className="stateMachine"><small>ESTADO DO REPOSITÓRIO</small><pre>{s.frames[step]}</pre><div className="stateDots">{s.frames.map((_,i)=><i className={i<=step?'on':''} key={i}/>)}</div></article><article className="advancedExplain"><small>O QUE ACONTECEU</small><p>{s.explain[step]}</p></article>{step<max&&<div className="advancedCommand"><small>PRÓXIMA AÇÃO</small><code>$ {s.commands[Math.min(step,s.commands.length-1)]}</code><button onClick={()=>setStep(x=>Math.min(max,x+1))}><Play size={15}/>Executar</button></div>}{step===max&&<div className="advancedDone"><Check/> Cenário concluído</div>}<button className="reset" onClick={()=>setStep(0)}><RotateCcw size={14}/> Reiniciar cenário</button></section>}