import{useState}from'react';import{Home,Compass,Terminal,User,GitBranch,Check,ChevronRight,Flame,BookOpen,Play,RotateCcw}from'lucide-react';
type FileState='modified'|'staged'|'committed'|'remote';
const commands=[['git status','Veja o que mudou'],['git add .','Prepare alterações'],['git commit','Crie um ponto no histórico'],['git push','Envie ao remoto']];
export default function App(){const[step,setStep]=useState(0);const[tab,setTab]=useState('Home');const state:FileState=(['modified','staged','committed','remote']as FileState[])[step];function run(){setStep(s=>Math.min(3,s+1))}
return <main><header><div className="brand"><span>&gt;_</span> DevFlow</div><div className="streak"><Flame size={16}/>12</div></header>
<section className="hero"><small>BOA NOITE, DEV 👋</small><h1>Entenda o código.<br/><em>Veja o fluxo.</em></h1><p>Aprenda desenvolvimento experimentando o que acontece por trás dos comandos.</p></section>
<section className="continue"><div className="sectionTitle"><b>Continue aprendendo</b><span>72%</span></div><article className="course"><div className="courseTop"><div className="gitIcon"><GitBranch/></div><div><small>GIT ESSENTIALS</small><h2>Do arquivo ao remoto</h2></div><ChevronRight/></div><div className="progress"><i/></div><p>Working Directory → Stage → Commit → Remote</p></article></section>
<section><div className="sectionTitle"><b>Visual Flow</b><span className="live">● INTERATIVO</span></div><div className="flow">{['Working','Staging','Commit','Remote'].map((x,i)=><div className={'node '+(i<=step?'active':'')} key={x}><span>{i<step?<Check size={15}/>:i+1}</span><small>{x}</small>{i<3&&<b>→</b>}</div>)}</div></section>
<section className="lab"><div className="sectionTitle"><b>Git Playground</b><button onClick={()=>setStep(0)}><RotateCcw size={14}/> reset</button></div><div className="file"><span>📄</span><div><b>App.java</b><small>{state.toUpperCase()}</small></div></div><div className="terminal"><div className="dots">● ● ● <span>TERMINAL</span></div><code><i>$</i> {step===0?'git add .':step===1?'git commit -m "feat: update"':step===2?'git push':'✓ Tudo sincronizado'}</code></div><button className="run" onClick={run} disabled={step===3}><Play size={17} fill="currentColor"/>{step===3?'Fluxo concluído':'Executar comando'}</button></section>
<section className="commands"><div className="sectionTitle"><b>Comandos essenciais</b><span>4 de 15</span></div>{commands.map((c,i)=><div className="cmd" key={c[0]}><span className={i<=step?'done':''}>{i<=step?<Check size={14}/>:i+1}</span><code>{c[0]}</code><small>{c[1]}</small></div>)}</section>
<div className="spacer"/><nav>{[[Home,'Home'],[Compass,'Explorar'],[Terminal,'Lab'],[User,'Perfil']].map(([Icon,label]:any)=><button className={tab===label?'selected':''} onClick={()=>setTab(label)} key={label}><Icon size={21}/><small>{label}</small></button>)}</nav></main>}