import{useState}from'react';import BranchLab from'./BranchLab';import'./branchLab.css';import{Home,Compass,Terminal,User,GitBranch,Check,ChevronRight,Flame,Play,RotateCcw,FolderGit2,BookOpen,Lock,ArrowLeft}from'lucide-react';
type Tab='Home'|'Explorar'|'Lab'|'Perfil';
const lessons=[['status','Inspecione seu repositório','git status'],['stage','Prepare arquivos para commit','git add .'],['commit','Registre uma versão','git commit -m "feat: update"'],['remote','Sincronize com o remoto','git push']];
const modules=[['Git Essentials','15 conceitos','72%','open'],['Branches & Merge','Em breve','0%','soon'],['Java Visual','Próximo módulo','0%','soon'],['Spring Boot','Planejado','0%','soon']];
export default function App(){const[tab,setTab]=useState<Tab>('Home');const[step,setStep]=useState(0);const[logs,setLogs]=useState<string[]>(['$ git status','modified: src/App.java']);const[challenge,setChallenge]=useState(false);const[branchMode,setBranchMode]=useState(false);
const state=['MODIFIED','STAGED','COMMITTED','SYNCED'][step];const cmd=lessons[step][2];
function run(){if(step===3)return;const output=step===0?'Changes staged for commit':step===1?'[main 8f13ab2] feat: update':'To github.com/devflow/project.git\n   42af320..8f13ab2  main -> main';setLogs(l=>[...l,'$ '+cmd,output]);setStep(s=>Math.min(3,s+1))}
function reset(){setStep(0);setLogs(['$ git status','modified: src/App.java']);setChallenge(false)}
return <main><header><button className="brand" onClick={()=>setTab('Home')}><span>&gt;_</span> DevFlow</button><div className="streak"><Flame size={16}/>12</div></header>
{tab==='Home'&&<><section className="hero"><small>DEVFLOW · V0.2</small><h1>Entenda o código.<br/><em>Veja o fluxo.</em></h1><p>Uma experiência visual para aprender engenharia de software experimentando.</p></section><section><div className="sectionTitle"><b>Continue aprendendo</b><span>{step+1}/4</span></div><button className="course clickable" onClick={()=>setTab('Lab')}><div className="courseTop"><div className="gitIcon"><GitBranch/></div><div><small>GIT ESSENTIALS</small><h2>Do arquivo ao remoto</h2></div><ChevronRight/></div><div className="progress"><i style={{width:(25*(step+1))+'%'}}/></div><p>Working Directory → Stage → Commit → Remote</p></button></section><section><div className="sectionTitle"><b>Mapa de aprendizado</b><button onClick={()=>setTab('Explorar')}>Ver tudo</button></div><div className="miniGrid"><article><GitBranch/><b>Git</b><small>Em andamento</small></article><article><FolderGit2/><b>Branches</b><small>Próxima etapa</small></article></div></section></>}
{tab==='Explorar'&&<><PageTitle title="Explorar" sub="Seu mapa de Engenharia de Software"/><div className="moduleGrid">{modules.map((m,i)=><button className="module" key={m[0]} disabled={m[3]==='soon'} onClick={()=>i===0&&setTab('Lab')}><div className="moduleIcon">{i===0?<GitBranch/>:<Lock/>}</div><div><b>{m[0]}</b><small>{m[1]}</small></div><span>{m[2]}</span></button>)}</div><div className="roadmap"><small>ROADMAP</small><h3>Git → Java → Spring → SQL → Docker</h3><p>O DevFlow cresce módulo por módulo, mantendo cada conceito visual, prático e testável.</p></div></>}
{tab==='Lab'&&<><PageTitle title="Git Playground" sub="Execute o fluxo. Veja o estado mudar."/><div className="labSwitch"><button className={!branchMode?'on':''} onClick={()=>setBranchMode(false)}>Fundamentos</button><button className={branchMode?'on':''} onClick={()=>setBranchMode(true)}>Branches & Merge</button></div>{branchMode?<BranchLab/>:<>
<div className="flow">{['Working','Staging','Commit','Remote'].map((x,i)=><div className={'node '+(i<=step?'active':'')} key={x}><span>{i<step?<Check size={15}/>:i+1}</span><small>{x}</small>{i<3&&<b>→</b>}</div>)}</div><section className="lab"><div className="labHead"><div><small>ARQUIVO ATUAL</small><b>📄 src/App.java</b></div><span className={'badge s'+step}>{state}</span></div><div className="terminal"><div className="dots">● ● ● <span>DEVFLOW TERMINAL</span></div><div className="screen">{logs.slice(-5).map((l,i)=><code key={i} className={l.startsWith('$')?'prompt':''}>{l}</code>)}{step<3&&<code className="next"><i>$</i> {cmd}</code>}</div></div><button className="run" onClick={run} disabled={step===3}><Play size={17} fill="currentColor"/>{step===3?'Repositório sincronizado':'Executar '+cmd.split(' ').slice(0,2).join(' ')}</button><button className="reset" onClick={reset}><RotateCcw size={14}/> Reiniciar laboratório</button></section><section><div className="sectionTitle"><b>O que aconteceu?</b><span>{step+1}/4</span></div><article className="explain"><b>{lessons[step][0].toUpperCase()}</b><h3>{lessons[step][1]}</h3><p>{step===0?'O arquivo ainda vive no Working Directory. git add prepara a alteração para o próximo snapshot.':step===1?'A alteração está na Staging Area. O commit vai registrar exatamente este estado no histórico local.':step===2?'Seu commit existe localmente. git push envia os commits novos para o repositório remoto.':'Local e remoto agora apontam para o mesmo commit. Você completou o fluxo básico.'}</p></article></section>{step===3&&<button className="challenge" onClick={()=>setChallenge(!challenge)}><BookOpen/> {challenge?'Desafio concluído: fluxo básico dominado ✓':'Concluir desafio Git #01'}</button>}</>}</>}
{tab==='Perfil'&&<><PageTitle title="Seu progresso" sub="A jornada começa pelo fundamento."/>
<div className="profileCard"><div className="avatar">&lt;/&gt;</div><h2>Dev Explorer</h2><p>Git Essentials · Nível 01</p><div className="stats"><div><b>{step+1}</b><small>etapas</small></div><div><b>1</b><small>módulo</small></div><div><b>12</b><small>streak</small></div></div></div><article className="about"><small>SOBRE ESTE PROJETO</small><h3>Construído para ensinar e demonstrar engenharia.</h3><p>React + TypeScript + Vite · arquitetura preparada para novos laboratórios interativos.</p></article></>}
<div className="spacer"/><nav>{[[Home,'Home'],[Compass,'Explorar'],[Terminal,'Lab'],[User,'Perfil']].map(([Icon,label]:any)=><button className={tab===label?'selected':''} onClick={()=>setTab(label)} key={label}><Icon size={21}/><small>{label}</small></button>)}</nav></main>}
function PageTitle({title,sub}:{title:string,sub:string}){return <section className="pageTitle"><small>DEVFLOW</small><h1>{title}</h1><p>{sub}</p></section>}