import{useState}from'react';import{Check,RotateCcw,Trophy}from'lucide-react';
const questions=[
['Prepare somente App.java','Você alterou App.java e .env. O segredo não pode entrar no commit.',['git add .','git add App.java','git commit App.java'],1,'git add App.java adiciona apenas o arquivo desejado ao stage.'],
['Desfaça com segurança','Um commit já foi enviado ao remoto compartilhado. Desfaça o efeito preservando o histórico.',['git reset --hard HEAD~1','git revert HEAD','git clean -fd'],1,'git revert cria um novo commit inverso sem reescrever o histórico compartilhado.'],
['Atualize antes de trabalhar','O remoto recebeu commits de outra pessoa. Integre essas mudanças à branch local.',['git pull','git init','git stash drop'],0,'git pull busca e integra as mudanças remotas.'],
['Guarde trabalho incompleto','Você precisa trocar para uma branch de hotfix, mas possui alterações ainda sem commit.',['git stash','git reset --hard','git revert HEAD'],0,'stash guarda temporariamente o trabalho sem exigir um commit.'],
['Histórico linear','Sua feature ficou atrás da main e você quer reposicionar seus commits locais sobre a base atual.',['git merge --abort','git rebase main','git clone main'],1,'rebase recria os commits da feature sobre a nova base.'],
['Traga só o hotfix','Outra branch tem três commits, mas você precisa aplicar somente um deles na main.',['git cherry-pick <hash>','git pull --all','git add <hash>'],0,'cherry-pick aplica a mudança de um commit específico na branch atual.'],
['Retire do stage','Você executou git add por engano, mas quer manter a edição no arquivo.',['git restore --staged arquivo','git clean -fd','git reset --hard'],0,'restore --staged retira do índice e preserva a alteração no Working Directory.'],
['Ignore um segredo','Qual entrada impede que o arquivo local .env seja incluído em novos commits?',['git hide .env','.gitignore: .env','git stash .env'],1,'O padrão .env no .gitignore evita que um arquivo ainda não rastreado seja adicionado.'],
['Inspecione antes do commit','Você quer ver as mudanças que já estão na Staging Area.',['git diff --staged','git status --remote','git log --working'],0,'git diff --staged mostra o diff entre o índice e o último commit.'],
['Branch nova','Crie feature/login e já mude para ela.',['git switch -c feature/login','git branch --merge feature/login','git checkout main'],0,'git switch -c cria a branch e muda para ela.']
] as const;
export default function ChallengeLab(){const[q,setQ]=useState(0);const[pick,setPick]=useState<number|null>(null);const[score,setScore]=useState(0);const done=q===questions.length;function choose(i:number){if(pick!==null)return;setPick(i);if(i===questions[q][3])setScore(s=>s+1)}function next(){setQ(x=>x+1);setPick(null)}function reset(){setQ(0);setPick(null);setScore(0)}if(done)return <section className="quizFinish"><Trophy size={38}/><small>GIT CHECKPOINT CONCLUÍDO</small><h2>{score}/{questions.length} corretas</h2><p>{score>=9?'Domínio excelente dos cenários do módulo.':score>=7?'Bom domínio. Reveja os cenários que geraram dúvida.':'Vale revisitar as aulas e laboratórios antes de tentar novamente.'}</p><button className="run" onClick={reset}><RotateCcw size={16}/>Refazer checkpoint</button></section>;const item=questions[q];return <section className="quiz"><div className="quizTop"><small>CHECKPOINT {q+1}/{questions.length}</small><span>{score*100} XP</span></div><div className="quizBar"><i style={{width:(q/questions.length*100)+'%'}}/></div><h2>{item[0]}</h2><p>{item[1]}</p><div className="quizOptions">{item[2].map((o,i)=>{const reveal=pick!==null;const cls=reveal?(i===item[3]?'correct':i===pick?'wrong':''):'';return <button className={cls} onClick={()=>choose(i)} key={o}><code>{o}</code>{reveal&&i===item[3]&&<Check size={17}/>}</button>})}</div>{pick!==null&&<div className={'feedback '+(pick===item[3]?'ok':'no')}><b>{pick===item[3]?'Correto ✓':'Resposta incorreta'}</b><p>{item[4]}</p><button onClick={next}>{q===questions.length-1?'Ver resultado':'Próximo →'}</button></div>}</section>}